api:
  host: iris-api
  port: 16649
  user: iris-frontend
  api_key: 'API_KEY'

flask:
  SECRET_KEY: 'secret'

auth:
  module: 'iris_frontend.auth.ldap'
  ldap_cert_path: 'ldap_cert.pem'
  ldap_url: 'ldaps://lca1-ldap-vip.corp.linkedin.com'
  ldap_user_suffix: '@linkedin.biz'

debug: true
